services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    environment:
      LDAP_BASE_DN: "dc=example,dc=org"
      LDAP_ORGANISATION: "Example Organization"
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_TLS: "false"
    volumes:
    - ./ldap/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/50-bootstrap.ldif
    ports:
    - "389:389"
    command: --copy-service
    restart: unless-stopped
  sendgrid:
    image: 'ykanazawa/sendgrid-maildev'
    environment:
    - 'SENDGRID_DEV_API_SERVER=:3030'
    - 'SENDGRID_DEV_API_KEY=SG.xxxxx'
    - 'SENDGRID_DEV_SMTP_SERVER=127.0.0.1:1025'
    ports:
    - '3030:3030'
    - '1080:1080'